<div class="topBlock">
	<div class="twitter">
		<p>
			Sprawdź nas na <a href="http://twitter.com/optimummediaomd">
				<img src="<?= $this->baseUrl; ?>/public/images/twitterlogo.png" alt="Logo Twittera" />
			</a>
		</p>
	</div>
	<div class="something">
		<p>
			Średnie CPP cennikowe w 4 stacjach głównych w sierpniu (vs sierpień 08) wzrosło o ok 6,5% (TG: 16 - 49)
		</p>
	</div>
</div>
<?php if( $this->addNews->cntItems ) : ?>
<div class="news">
	<h3>Aktualności</h3>
	<?php for( $i = 0, $cnt = $this->addNews->length(); $i < $cnt; $i++ ) :?>
		<p><?php echo $this->addNews[$i]->getLead() ?></p>
	<?php endfor ?>
</div>
<?php endif; ?>