<div id="navigation">
	<ul>
		<li class="first"><a href="<?= $this->baseUrl; ?>/" class="hi">&nbsp;</a></li>
		<li class="second"><a href="<?= $this->baseUrl; ?>/aktualnosci.html">Aktualności</a></li>
		<li><a href="<?= $this->baseUrl; ?>/o-nas.html">O nas</a></li>
		<li><a href="<?= $this->baseUrl; ?>/narzedzia.html">Narzędzia</a></li>
		<li><a href="<?= $this->baseUrl; ?>/analizy-i-publikacje.html">Analizy i publikacje</a></li>
		<li><a href="<?= $this->baseUrl; ?>/omd-school.html">OMD School</a></li>
		<li><a href="<?= $this->baseUrl; ?>/siec-omd.html">Sieć OMD</a></li>
		<li class="last"><a href="<?= $this->baseUrl; ?>/kontakt.html">Kontakt</a></li>
	</ul>
</div>
