<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<?php echo $this->render('header.phtml'); ?>
	<body>
    <div id="site">
			<?php echo $this->render('toplogo.phtml'); ?>
			<?php echo $this->render('navigation.phtml'); ?>
			<div id="content">
				<div id="additional">
					<?php echo $this->render('additional.phtml'); ?>
				</div>
				<div id="main">
                    <?php echo $this->layout()->content ?>
				</div>
			</div>
			<?php echo $this->render('footer.phtml'); ?>
		</div>
		
		<script type="text/javascript">
		var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
		document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
		<script type="text/javascript">
		try {
		var pageTracker = _gat._getTracker("UA-12484762-1");
		pageTracker._trackPageview();
		} catch(err) {}</script>
		
	</body>
</html>