<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<?php echo $this->render('header.phtml'); ?>
	<body>
    <div id="site">
			<?php echo $this->render('toplogo.phtml'); ?>
			<?php echo $this->render('navigation.phtml'); ?>
			<div id="content">
				<div id="additional">
					<?php echo $this->render('additional.phtml'); ?>
				</div>
				<div id="main">
                    <?php echo $this->layout()->content ?>
				</div>
			</div>
			<?php echo $this->render('footer.phtml'); ?>
		</div>
	</body>
</html>