<div class="aktualnosci">
	<h1 class="borderBottom">Aktualności</h1>
	
	<?php if( $this->mainNews ) : ?>
    	<ul class="news">
    	<?php for( $i = 0, $cnt = $this->mainNews->length(); $i < $cnt; $i++ ) :?>
    	<li>
        	<a href="<?= $this->baseUrl; ?>/artykul.html?id=<?php echo $this->mainNews[$i]->getId(); ?>">
        		<span class="h3"><?php echo $this->mainNews[$i]->getTitle() ?></span>
        		<span class="date"><?php echo $this->mainNews[$i]->getAddDate() ?></span>
        		<?php if( $i < 3 ) : ?>
        			<span class="p"><?php echo $this->mainNews[$i]->getLead() ?></span>
        		<?php endif; ?>
        	</a>
		</li>
    	<?php endfor; ?>
    	</ul>
	<?php endif; ?>		
</div>