<div id="news">
	<h1 class="borderBottom">Aktualności</h1>
	
	<?php if( isset( $this->mainNews[0] ) ): ?>
    	<ul>
    	<?php for( $i = 0, $cnt = count( $this->mainNews ); $i < $cnt; $i++ ) :?>
    	<li class="singleUnderline">
        	<a href="<?= $this->baseUrl; ?>/artykul.html?id=<?php echo $this->mainNews[$i]->getId(); ?>">
        		<span class="title"><?php echo $this->mainNews[$i]->getTitle() ?></span></a>
        		<span class="date"><?php echo $this->mainNews[$i]->getEnableDate() ?></span>
        		<?php // if( $i < 3 ) : ?>
        			<span class="p"><?php echo $this->mainNews[$i]->getLead(); ?> </span>
							<a class="more" href="<?= $this->baseUrl; ?>/artykul.html?id=<?php echo $this->mainNews[$i]->getId(); ?>">
		        		Czytaj&nbsp;dalej&nbsp;&raquo;</a>
        		<?php // endif; ?>
        	
		</li>
    	<?php endfor; ?>
    	</ul>
	<?php endif; ?>		
</div>
<div class="navigation">
	<ul>
		<?php if( $this->mainNews->getNavigation()->getPrevPack() ) : ?><li>&laquo; <a href="<?= $this->baseUrl; ?>/aktualnosci.html?p=<?php echo $this->mainNews->getNavigation()->getPrevPack() ?>">Nowsze informacje</a></li><?php endif; ?>
		<?php if( $this->mainNews->getNavigation()->getNextPack() ) : ?><li><a href="<?= $this->baseUrl; ?>/aktualnosci.html?p=<?php echo $this->mainNews->getNavigation()->getNextPack() ?>">Wcześniejsze informacje</a> &raquo;</li><?php endif; ?>
	</ul>
</div>