<div id="publications">
    <h1 class="borderBottom">Analizy i publikacje 2009</h1>
    
    <ul class="dotted">
			<li><a href="/publikace-styczen-2009.html">Grudzień</a></li>
			<li><a href="/publikace-styczen-2009.html">Listopad</a></li>
			<li><a href="/publikace-styczen-2009.html">Październik</a></li>
			<li><a href="/publikace-styczen-2009.html">Wrzesień</a></li>
			<li><a href="/publikace-styczen-2009.html">Sierpień</a></li>
			<li><a href="/publikace-styczen-2009.html">Lipiec</a></li>
			<li><a href="/publikace-styczen-2009.html">Czerwiec</a></li>
			<li><a href="/publikace-styczen-2009.html">Maj</a></li>
			<li><a href="/publikace-styczen-2009.html">Kwiecień</a></li>
			<li><a href="/publikace-styczen-2009.html">Marzec</a></li>
			<li><a href="/publikace-styczen-2009.html">Luty</a></li>
			<li><a href="/publikace-styczen-2009.html">Styczeń</a></li>
		</ul>
</div>
