<div class="image">
	<img class="bigPicture" src="<?= $this->baseUrl; ?>/public/images/main-omd-team.png" alt="" />
</div>
<div class="halfMain">
	<h2 class="red">Eskobo goowy manjan. Treść tetowa da napisui po lewej stronie. Realizuj z nami!</h2>
	<p>Naprawdę ciekawe informacje o naszej firmie, które powinny spowoować, że będziesz chętnie z nami współpracował i robił dużo projektów.</p>
	<div class="contact">
		<a href="<?= $this->baseUrl; ?>/kotankt.html">Skontaktuj się z <span class="gray">O</span><span class="red">M</span><span class="gray">D</span></a>.
	</div>
	<p>Jeszcze krótka informacja, <span class="red">która może</span> Cię zainteresować!</p>
</div>

<div class="halfMain">
	<h2 class="gray">Współpraca z naszą firmą zaowocuje szybko zauważalnymi zyskami kampnii reklamowch!</h2>
	<p>Kolejny, jeszcez bardziej ciekawy informacje o naszej firmie, które powinny spowoować, że będziesz chętnie z nami współpracował i robił dużo projektów.</p>
</div>