<div class="kontakt">
	<h2>Kontakt</h2>
	
	<p><strong>OMD Sp. z o.o.<br />oddział Optimum Media OMD</strong></p>
	<p>ul. Ibisa 14<br />02-812 Warszawa</p>
	<p>		
		<strong>Marta Wiercińska</strong><br />
		tel. (+4822) 32 01 200<br />
		fax: (+4822) 32 01 201<br />
		mail: <a href="mailto:marta.wiercinska@optimum-media.pl">marta.wiercinska@optimum-media.pl</a>
	</p>
	<p>
		NIP: 951 220 49 28<br />
		KRS: 000 027 24 33<br />
		Sąd Rejonowy dla m. st. Warszawy<br />
		XIII Wydział Gospodarczy KRS<br />
		Kapitał: 26 235 500,00 zł
	</p>
	<br />
</div>