<div class="kontakt">
	
	<div class="half right">
		<form method="post">
    		<h2>Formularz kontaktowy</h2>
    		
    		<p>Aby się z nami skontaktować możesz także wypełnić poniższy formularz:</p>
    		<p>
    			<label for="institution">Instytucja</label><br/>
    			<input class="text" type="text" name="institution" id="institution" />		
    		</p>
    		<p>
    			<label for="name">Imię i nazwisko</label><br/>
    			<input class="text" type="text" name="name" id="name" />	
    		</p>
    		<p>
    			<label for="email">E-mail</label><br/>
    			<input class="text" type="text" name="email" id="email" />		
    		</p>
    		<p>
    			<label for="telephone">Telefon</label><br/>
    			<input class="text" type="text" name="telephone" id="telephone" />		
    		</p>
    		<p>
    			<label for="message">Wiadomość</label><br/>
    			<textarea class="text" name="message" id="message" rows="5"></textarea>		
    		</p>
    		<p><input class="right" type="submit" value="Wyślij" /></p>
		</form>
	</div>

	<div class="half">
    	<h2>Kontakt</h2>
    	
    	<p><strong>OMD Sp. z o.o.<br />oddział Optimum Media OMD</strong></p>
    	<p>ul. Ibisa 14<br />02-812 Warszawa</p>
    	<p>		
    		tel. (+4822) 32 01 200<br />
    		fax: (+4822) 32 01 201<br />
    		mail: <a href="mailto:info@optimum-media.pl">info@optimum-media.pl</a>
    	</p>
    	<p>
    		NIP: 951 220 49 28<br />
    		KRS: 000 027 24 33<br />
    		Sąd Rejonowy dla m. st. Warszawy<br />
    		XIII Wydział Gospodarczy KRS<br />
    		Kapitał: 26 235 500,00 zł
    	</p>
	</div>
	
	<div class="left full">
		<br/>
		<h2>Mapka</h2>
		<iframe width="300" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://mapy.google.pl/maps?f=q&amp;source=s_q&amp;hl=pl&amp;geocode=&amp;q=Ibisa+14&amp;sll=52.141048,21.020708&amp;sspn=0.017515,0.038581&amp;ie=UTF8&amp;ll=52.141653,21.019893&amp;spn=0.007901,0.012875&amp;z=15&amp;output=embed"></iframe>	
	</div>
	
</div>