<div id="sitemap">
<h1 class="borderBottom">Mapa strony</h1>
	<ul>
		<li><a href="<?= $this->baseUrl; ?>/">Strona główna</a></li>
		<li>
			<ul class="dotted">
				<li><a href="<?= $this->baseUrl; ?>/aktualnosci.html">Aktualności</a></li>
				<li><a href="<?= $this->baseUrl; ?>/o-nas.html">O nas</a></li>
				<li><a href="<?= $this->baseUrl; ?>/narzedzia.html">Narzędzia</a></li>
				<li><a href="<?= $this->baseUrl; ?>/analizy-i-publikacje.html">Analizy i publikacje</a></li>
				<li><a href="<?= $this->baseUrl; ?>/omd-school.html">OMD School</a></li>
				<li><a href="<?= $this->baseUrl; ?>/siec-omd.html">Sieć OMD</a></li>
				<li><a href="<?= $this->baseUrl; ?>/kontakt.html">Kontakt</a></li>
			</ul>
		</li>
	</ul>
</div>