<div class="narzedzia">
    <h2>Narzędzia OMD</h2>
    
    <div class="paragraph">
        <p><img src="public/images/tools_checkmate.gif" alt="Checkmate" /></p>
        <p><b>OMD Checkmate</b> to <b>model strategicznego planowania mediów</b>. Spójny system myślenia używany we wszystkich oddziałach OMD na świecie, który został opracowany na bazie współpracy z czołowymi międzynarodowymi firmami oraz agencjami kreatywnymi.</p>
        <p>Celem OMD Checkmate jest <b>rozwijanie innowacyjnych i efektywnych rozwiązań</b> komunikacyjnych służących budowaniu marki i pozycji rynkowej Klientów. Wyniki są efektem wspólnej zespołowej pracy Klienta, Agencji i Domu Mediowego. Odnosząc się do metafory szachów, „szach-mat” stanowi <b>przewodnik strategicznego myślenia</b>: dynamicznego analizowania sytuacji biznesowej, opracowania długofalowej strategii rozwoju i taktyk służących do jej realizowania.</p>
    </div>
    
    <div class="paragraph">
        <p><img src="public/images/tools_curve.gif" alt="Checkmate" /></p>
        <p><b>Software sieciowy</b>, który daje odpowiedź, jaka powinna być efektywna częstotliwość kontaktu z przekazem reklamowym w zależności od stawianych sobie celów kampanii (np. ) <b>wzrost świadomości marki</b>.</p>
    </div>
    
    <div class="paragraph">
        <p><img src="public/images/tools_phaser.gif" alt="Checkmate" /></p>
        <p><b>Modelowanie / "flighting"</b> kampanii telewizyjnych.</p>
    </div>
    
    <div class="paragraph">
        <p><img src="public/images/tools_lookie.gif" alt="Checkmate" /></p>
        <p><b>Software sieciowy</b> do planowania i kupowania telewizji. Został zaadaptowany do warunków polskich. Nie tylko pozwala <b>przewidywać oglądalność</b> z dużą dokładnością, ale także <b>optymalizować parametry</b> kampanii ze względu na koszt dotarcia oraz zasięg efektywny. (narzędzie przejęte z OMD).</p>
    </div>
    
    <div class="paragraph">
        <p><img src="public/images/tools_datareporter.gif" alt="Checkmate" /></p>
        <p><b>Software lokalny</b> do raportowania wydatków konkurencji. Ten zaawansowany program pozwala na comiesięczne <b>raportowanie</b> do klientów ich wydatków, za pomocą kliknięcia jednym guzikiem. Uzyskuje się raport składający się z kilkunastu zakładek, a na każdej z nich jest inna <b>analiza</b> dotycząca <b>danego medium</b>. Daje możliwość śledzenia ruchu wydatków nawet małych lokalnych gazet (narzędzie Optimum Media).</p>
    </div>
    
    <div class="paragraph">
        <p><img src="public/images/tools_response.gif" alt="Checkmate" /></p>
        <p><b>Model planowania</b> kampanii responsowych mających na celu <b>generowanie interakcji</b> z odbiorcą (infolinia, kupon) oraz <b>pomiaru efektywności</b> użytych kanałów komunikacji.</p>
    </div>
    
    <div class="paragraph">
        <p><img src="public/images/tools_viewer.gif" alt="Checkmate" /></p>
        <p><b>Lokalne narzedzie</b> dajace możliwość <b>śledzenia wyników badania</b> brand tracking. To badanie prowadzone <b>metodą cati</b>. Bada spontaniczną, wspomaganą <b>świadomość marki</b> oraz <b>świadomość reklamy</b>. Pytania dotyczą także zamiaru zakupu bądź fakt zakupu w przyszłości, co daje możliwość obserwowania efektów kampanii z tygodnia na tydzień i szybką reakcję gdy nie spełniają one wcześniej przyjętych założeń. Na podstawie danych brand trackingu buduje się <b>modele ekonometryczne</b> symulujące różnorakie scenariusze wpływu inwestycji w mediach na indeksy świadomościowe oraz sprzedaż (obsługą jego zajmuje się OMD Metrix).</p>
    </div>
    
    <div class="paragraph">
        <p><img src="public/images/tools_pressplanner.gif" alt="Checkmate" /></p>
        <p><b>Optymalizacja i planowanie kampanii prasowych</b> w oparciu o surowe dane (wprowadzone w 2004 roku).</p>
    </div>
</div>