<div class="narzedzia">
	<h1>Narzędzia</h1>
	<a name="top">
	<p class="borderBottom paragraph">Optimum Media OMD korzysta z dostępnych na rynku badań mediów oraz analiz zachowań konsumentów, jednak na bieżąco także śledzi nowe możliwości i trendy rozwoju mediów, by oferować swoim Klientom jak najciekawsze i za razem efektywne rozwiązania w planowaniu kampanii w mediach. W tym celu uczestniczy w budowie i inspiruje zespół Software Development do tworzenia narzędzi planerskich dopasowanych do realiów polskiego rynku i polskich konsumentów. Dodatkowo dzięki lokalnym projektom badawczym zespół Optimum Media OMD pogłębia wiedzę nt. efektywności mediów i dopasowania komunikacji do konkretnych założeń marketingowych Klientów.</p></a>
	<h2>Własne projekty badawcze</h2>
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/omniscope.png" alt="Omniscope logo" />
		<h3>Omniscope</h3>
		<p>Wielotematyczne badanie omnibusowe OMD Metrisc, realizowane na ogólnopolskiej próbie miejskiej. Projekt Omniscope otwiera Klientom możliwość zlecania pojedyńczych pytań o dowolnie określonej tematyce bez konieczności zlecania odrębnego badania.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/mindscope.gif" alt="Mindscope logo" />
		<h3>Mindscope</h3>
		<p>Badanie siły poszczególnych kanałów komunikacji dla danej grupy docelowej i kategorii produktów. Umożliwia określenie perswazyjności siły oddziaływania kanałów komunikacji (index perswazyjności).</p>
	</div>
	
	<div class="tool">
		<h3>Brandscope</h3>
		<p>Identyfikacja najważniejszych wymiarów percepcji marek  w danej kategorii- odtworzenie pozycjonowania w odbiorze potencjalnych konsumentów, identyfikacja silnych i słabych stron. Analiza zmian w percepcji marki w wyniku przeprowadzonych działań reklamowych.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/lifescpe.gif" alt="Lifescope logo" />
		<h3>Lifescope</h3>
		<p>Badanie umożliwiające precyzyjne rozpoznanie "dnia z życia" grupy docelowej i dzięki temu precyzyjne osadzenie komunikatu w kontekście.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/mediascope.gif" alt="Mediascope logo" />
		<h3>Mediascope</h3>
		<p>Stały projekt badawczy Macroscope, mający na celu pogłębianie wiedzy o efektywności kanałów komunikacji. Pierwsza część - badanie wpływu różnych mediów oraz ilości powtórzeń na budowanie zapamiętywania przekazu reklamowego. Przeprowadzona przez Macroscope w okresie czerwca-grudnia 2004. Rewolucyjne wyniki, podważające rutynowe podejście do planowania mediów.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/brandtracking.gif" alt="Brandtracking logo" />
		<h3>Brandtracking</h3>
		<p>Badania Brand Tracking, prowadzone przez OMD, służące do ciągłego monitorowania pozycji marki i jej konkurentów, ewaluacji wyników kampanii i stosowanych strategii mediowych. Macroscope oferuje swoim Klientom planowanie kampanii reklamowych oraz bieżącą optymalizację działań reklamowych w oparciu o wnioski wypływające z Brand Trackingu.</p>
	</div>
	
	<div class="tool">
		<h3>Market potential scope</h3>
		<p>Określa udział poszczególnych grup potencjalnych konsumentów w całkowitej konsumcji produktu (marki/kategorii produktowej). Ocenia wskaźnik potencjału konsumpcyjnego poszczególnych grup konsumenckich. Identyfikuje najważniejsze bariery w rozwoju konsumpcji marki/kategorii produktowej. Rekomenduje optymalny dobór grup celowych oraz strategii komunikacyjnej niwelującej wykryte bariery konsumpcji. Ponadto analizuje wpływy kampanii reklamowych nas strukturę udziału poszcególnych grup w konsumpcji produktu.</p>
	</div>
	
	<h2>Lokalne narzędzia OMD</h2>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/adeffect.gif" alt="AdEffect logo" />
		<h3>AdEffect</h3>
		<p>AdEffect jest narzędzie do analizy wyników modelu ekonometrycznego, prognozującego efekty świadomościowe kampanii w zależności od wybranych rozwiązań reklamowych. Narzędzie zostało opracowane przez <a href="http://www.omgmetrics.pl/?mod=adeffect">OMG Metrics</a> w ramach unikalnego projektu ekonometrycznego, opartego na wieloletnim monitoringu wpływu aktywności reklamowej na wskaźniki świadomości marek i reklam na polskim rynku.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/tvwarrior.gif" alt="TV Warrior logo" />
		<h3>TV Warrior</h3>
		<p>TV Warrior to autorski program OmnicomMediaGroup do optymalizacji i planowania kampanii TV, zbudowany z 4 modułów wspierających zakup w poszczególnych etapach:
			<ul>
				<li><strong>Moduł predykcji oglądalności</strong> - Umożliwia centralne i zautomatyzowane przewidywanie oglądalności przyszłych bloków reklamowych dla 9 stacji TV, ok. 15 tys. bloków, ok. 120 różnych grup celowych.</li>
				<li><strong>Moduł optymalizacji</strong> - Moduł wybiera optymalne breaki ze wszystkich stacji jednocześnie zamiast predefiniować udziały poszczególnych stacji. Udziały stacji są konsekwencją optymalizacji nie odwrotnie.</li>
				<li><strong>Moduł zakupu</strong> - Proces zarządzania kampanią: generowania, wysyłki, wprowadzania i aktualizacji zleceń jest zautomatyzowany. Pozwala to planerom OMG na realizowanie zamówień przed konkurencją, szczególnie ważną przy zakupie z cennika.</li>
				<li><strong>Moduł raportowania/kontroli</strong> - Integruje dane pochodzące z różnych źródeł (prebuy, badania mediów, dane finansowe, predykcje oglądalności) i automatycznie generuje raporty. Umożliwia to błyskawiczną reakcję na nieprzewidziane okoliczności i korekty planów oraz pełną kontrolę kampanii.</li>
			</ul>
			</p>
	</div>

	<div class="tool">
		<h3>Outdoor Media Integrator</h3>
		<p>Aplikacja OMI jest innowacyjnym i unikatowym narzędziem do selekcji nośników i optymalizacji kampanii outdoorowych. Outdoor Media Integrator  to jedyne na rynku narzędzie służące do:
			<ul>
				<li>optymalnego rozplanowania kampanii w obrębie danej aglomeracji, z możliwością efektywnej topograficznej selekcji ofert różnych typów nośników</li>
				<li>weryfikacji lokalizacji konfliktowych, np. nośników zlokalizowanych zbyt blisko siebie i oddziaływujących na te same strumienie ruchu odpowiedniego zaplanowania kampanii kierunkowych (z nośnikami naprowadzającymi na wybrany obiekt)</li>
				<li>dobór nośników do kampanii na podstawie ich bliskości względem strategicznych punktów w topografii miast tzw. POI, pozwalające na dobór nośników w miejscach największego prawdopodobnego zagęszczenia grupy docelowej.</li>
			</ul>
		</p>
	</div>
	
	<h2>Sieciowe narzędzia OMD</h2>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/checkmate.gif" alt="OMD Checkmate logo" />
		<h3>OMD Checkmat</h3>
		<p>OMD Checkmate to model strategicznego planowania mediów. Spójny system myślenia używany we wszystkich oddziałach OMD na świecie, który został opracowany na bazie współpracy z czołowymi międzynarodowymi firmami oraz agencjami kreatywnymi. o Celem OMD Checkmate jest rozwijanie innowacyjnych i efektywnych rozwiązań komunikacyjnych służących budowaniu marki i pozycji rynkowej Klientów.  Wyniki są efektem wspólnej zespołowej pracy Klienta, Agencji i Domu Mediowego. Odnosząc się do metafory szachów, "szach-mat" stanowi przewodnik strategicznego myślenia: dynamicznego analizowania sytuacji biznesowej, opracowania długofalowej strategii rozwoju i taktyk służących do jej realizowania.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/curve.gif" alt="OMD Curve logo" />
		<h3>OMD Curve</h3>
		<p>Program do modelowania "energii marki" i określania optymalnej efektywnej częstotliwości na bazie wewnętrznych i zewnętrznych uwarunkowań strategii komunikacji.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/viewer.gif" alt="OMD Viewer logo" />
		<h3>OMD Viewer</h3>
		<p>Narzędzie dające możliwość śledzenia wyników badania Brand Traking.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/pressplanner.gif" alt="OMD PressPlanner logo" />
		<h3>OMD PressPlanner</h3>
		<p>Program optymalizujący i planujący kampanie prasowe w oparciu o surowe dane.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/datareporter.gif" alt="OMD DataReporter logo" />
		<h3>OMD DataReporter</h3>
		<p>Spójny system raportowania działań mediowych konkurencji, służący do przygotowania regularnych raportów i analiz ad-hoc.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/response.gif" alt="OMD Response logo" />
		<h3>OMD Response</h3>
		<p>Model planowania kampanii responsowych mających na celu generowanie interakcji z odbiorcą (infolinia, kupon) oraz pomiaru efektywności użytych kanałów komunikacji.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/curve.gif" alt="Omniscope logo" />
		<h3>OMD Curve</h3>
		<p>Program do modelowania "energii marki" i określania optymalnej efektywnej częstotliwości na bazie wewnętrznych i zewnętrznych uwarunkowań strategii komunikacji.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/palette.gif" alt="OMD Palette logo" />
		<h3>OMD Palette</h3>
		<p>Pomaga planerom w podejmowaniu decyzji, poprzez lepszy wybór kanałów przekazu, lepsze tarpetowanie i lepszą selekcję mediów. Ponad to, w pełni dopasowywuje sie do wymagań klientów. Palette jest częścią Brain Boxu OMD.</p>
	</div>