<div class="onas">
    <h2>Kim jesteśmy</h2>
    <p>Cechą, która nas wyróżnia jest <b>innowacyjność</b>. Po pierwsze operacyjna, ponieważ na każdym kroku staramy się wprowadzać w życie nowe pomysły od codziennej pracy poczynając.</p>
    <p>Innowacyjność to także <b>kreatywność</b> w mediach, czyli niestandardowe metody dotarcia do grupy celowej. Mają one skutkować w wymiernych <b>korzyściach</b> dla Klienta. Nie chodzi nam o bycie kreatywnym dla samej kreatywności, tylko o to, aby te nowe sposoby wykorzystania mediów, czy też nowe media, prowadziły do <b>lepszej komunikacji</b> z grupą docelową.</p>
    <p>Innowacyjność dzielimy na: zewnętrzną - przy tworzeniu nieszablonowych i skutecznych kampanii oraz wewnętrzną - przy dążeniu do doskonałości operacyjnej, po to żeby maksymalnie szybko i bezbłędnie odpowiadać na <b>zapotrzebowania Klientów</b>.</p>
    <p>Warunkiem innowacyjności jest autonomia, dlatego stworzyliśmy firmę nieskrępowaną ani biurokracją, ani sztywnymi normami, ani tradycją, ani historią. Unikamy wszelkiej uznaniowości. Koncentrujemy się na patrzeniu w przód. <b>Wierzymy, że nie ma rzeczy niemożliwych</b>.</p>
</div>