<h2>Sieć OMD</h2>
<p>Tutaj kilka informacji o związku z OMD z OMD.COM, trzeba będzie dodać treść...</p>

<p>OMD należy do jednego z największych holdingów komunikacyjnych na świecie – OmnicomGroup, notowanego na Nowojorskiej Giełdzie Papierów Wartościowych. Sprawdź stronę: <a target="_blank" href="http://www.omd.com">www.omd.com</a>

	</p>
	
	<a target="_blank" href="http://www.omd.com"><img src="<?= $this->baseUrl; ?>/public/images/omd.gif" alt="OMD School" /></a>