<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
   <head>
   	  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title><?php echo $this->escape($this->title); ?></title>
      <link rel="stylesheet" type="text/css" href="http://webascrazy.net/js/ext/resources/css/ext-all.css" />
      <script type="text/javascript" src="http://webascrazy.net/js/ext/adapter/ext/ext-base-debug.js"></script>
   	  <script type="text/javascript" src="http://webascrazy.net/js/ext/ext-all-debug.js"></script>
   	  <script type="text/javascript" src="<?php echo $this->publicUrl; ?>scripts/omd/Omd.Langpl.js"></script>
   	  <script type="text/javascript" src="<?php echo $this->publicUrl; ?>scripts/omd/Omd.Viewport.js"></script>
   	  <script type="text/javascript">
   	  	  Ext.namespace( 'Omg' );
   	  	  Omg.publicUrl = '<?php echo $this->publicUrl; ?>';
   	  </script>
   </head>

   <body>
	    <div id="west" class="x-hide-display"></div>
		
		<div id=categories class="x-hide-display"></div>
		
		<div id="article" class="x-hide-display"></div>

   </body>
</html>