<div id="news">
	<h1 class="borderBottom">Aktualności</h1>
	
	<?php if ( $this->mainNews ): ?>
    	<ul>
    	<?php for( $i = 0, $cnt = $this->mainNews->length(); $i < $cnt; $i++ ) :?>
    	<li class="singleUnderline">
        	<a href="<?= $this->baseUrl; ?>/artykul.html?id=<?php echo $this->mainNews[$i]->getId(); ?>">
        		<span class="title"><?php echo $this->mainNews[$i]->getTitle() ?></span></a>
        		<span class="date"><?php echo date("Y-m-d", strtotime($this->mainNews[$i]->getEnableDate())) ?></span>
        		<?php if( $i < 3 ) : ?>
        			<span class="p"><?php echo $this->mainNews[$i]->getLead(); ?> </span>
							<a class="more" href="<?= $this->baseUrl; ?>/artykul.html?id=<?php echo $this->mainNews[$i]->getId(); ?>">
		        		czytaj dalej ></a>
        		<?php endif; ?>
        	
		</li>
    	<?php endfor; ?>
    	</ul>
	<?php endif; ?>		
</div>