<div id="publications">
	<h1 class="borderBottom">Analizy i publikacje</h1>
	
	<?php if( isset( $this->mainNews[0] ) ): ?>
    	<ul>
    	<?php for( $i = 0, $cnt = count( $this->mainNews ); $i < $cnt; $i++ ) :?>
    	<li class="singleUnderline">
        	<a href="<?= $this->baseUrl; ?>/artykul.html?id=<?php echo $this->mainNews[$i]->getId(); ?>">
        		<span class="title"><?php echo $this->mainNews[$i]->getTitle() ?></span></a>
        		<span class="date"><?php echo date("Y-m-d", strtotime($this->mainNews[$i]->getEnableDate())) ?></span>
        		<?php // if( $i < 3 ) : ?>
        			<span class="p"><?php echo $this->mainNews[$i]->getLead(); ?> </span>
							<a class="more" href="<?= $this->baseUrl; ?>/artykul.html?id=<?php echo $this->mainNews[$i]->getId(); ?>">
		        		Zobacz publikację »</a>
        		<?php // endif; ?>
        	
		</li>
    	<?php endfor; ?>
    	</ul>
	<?php endif; ?>		
</div>
<div class="navigation">
	<ul>
		<?php if( $this->mainNews->getNavigation()->getPrevPack() ) : ?><li>&laquo; <a href="<?= $this->baseUrl; ?>/analizy-i-publikacje.html?p=<?php echo $this->mainNews->getNavigation()->getPrevPack() ?>">poprzednie</a></li><?php endif; ?>
		<?php if( $this->mainNews->getNavigation()->getNextPack() ) : ?><li><a href="<?= $this->baseUrl; ?>/analizy-i-publikacje.html?p=<?php echo $this->mainNews->getNavigation()->getNextPack() ?>">następne</a> &raquo;</li><?php endif; ?>
	</ul>
</div>

<!--
<div id="publications">
    <h1 class="borderBottom">Analizy i publikacje 2009</h1>

		<ul class="dotted">
			<li><a href="/publikace-styczen-2009.html">Grudzień</a></li>
			<li><a href="/publikace-styczen-2009.html">Listopad</a></li>
			<li><a href="/publikace-styczen-2009.html">Październik</a></li>
			<li><a href="/publikace-styczen-2009.html">Wrzesień</a></li>
			<li><a href="/publikace-styczen-2009.html">Sierpień</a></li>
			<li><a href="/publikace-styczen-2009.html">Lipiec</a></li>
			<li><a href="/publikace-styczen-2009.html">Czerwiec</a></li>
			<li><a href="/publikace-styczen-2009.html">Maj</a></li>
			<li><a href="/publikace-styczen-2009.html">Kwiecień</a></li>
			<li><a href="/publikace-styczen-2009.html">Marzec</a></li>
			<li><a href="/publikace-styczen-2009.html">Luty</a></li>
			<li><a href="/publikace-styczen-2009.html">Styczeń</a></li>
		</ul>
</div>
-->