<div class="lead">
	<a href="<?= $this->baseUrl; ?>/kontakt.html">
		<img class="bigPicture" src="<?= $this->baseUrl; ?>/public/images/omd-map-pl.png" alt="Mapa OMD" />
	</a>
</div>
<div class="halfMain">
	<img class="bigPicture" src="<?= $this->baseUrl; ?>/public/images/text-sg1.png" alt="OMD" />
	<p>należący do globalnej sieci <span class="gray">o</span>m<span class="gray">d</span> uznanej przez <span class="italic">the gunn report for media</span> za "the most creative media agency in the world" czterokrotnie z rzędu od 2005!</p>
</div>

<div class="halfMain leftBorder">
	<img class="bigPicture" src="<?= $this->baseUrl; ?>/public/images/text-sg2.png" alt="OMD" />
	<p><a class="bigPicture" href="<?= $this->baseUrl; ?>/kontakt.html"><img src="<?= $this->baseUrl; ?>/public/images/contactus.png" alt="OMD" /></a></p>
	<p>Chętnie przedstawimy ci, w jaki sposób efektywnie inwestujemy budżety mediowe.</p>
	<p><a href="<?= $this->baseUrl; ?>/narzedzia.html"><img src="<?= $this->baseUrl; ?>/public/images/checktools.png" alt="OMD" /></a></p>

</div>