<div class="image">
	<a href="<?= $this->baseUrl; ?>/kontakt.html">
		<img class="bigPicture" src="<?= $this->baseUrl; ?>/public/images/omd-map-pl.jpg" alt="Mapa OMD" />
	</a>
</div>
<div class="halfMain">
	<p class="uppercase gray big">optimum media o<span class="red">m</span>d</p>
	<p class="uppercase red big">najbardziej doświadczony dom mediowy w polsce</p>
	<p class="uppercase red big">należący do globalnej sieci <span class="gray">o</span>m<span class="gray">d</span> uznanej przez <span class="italic">the gunn report for media</span> za <span class="gray">"the most creative media agency in the world"</span> czterokrotnie z rzędu od 2005!</p>
</div>

<div class="halfMain">
	<p class="uppercase red big">zapraszamy!</p>
	<p><a class="big" href="<?= $this->baseUrl; ?>/kontakt.html">Skontaktuj się z nami!</a></p>
	<p class="uppercase big red">chętnie przedstawimy ci, w jaki sposób efektywnie inwestujemy budżety mediowe</p>
	<p><a class="big" href="<?= $this->baseUrl; ?>/narzedzia.html">Poznaj nasze Narzędzia!</a></p>

</div>