<div id="contact">

	<div class="half left">
    	<h1 class="borderBottom"><?php echo $this->article->getTitle() ?></h1>
				<?php echo $this->article->getContent() ?>
	</div>
	
	<div class="half left">
		<?php if( !$this->message ) :?>
			<h1 class="borderBottom">Formularz kontaktowy</h1>
  		
  		<p>Aby się z nami skontaktować możesz także wypełnić poniższy formularz: (* - pole wymagane)</p>
		<?php echo $this->form ?>

		<?php else :?>
			<p class="center"><br/><br/><br/><br/><br/><?php echo $this->message ?></p>
		<?php endif; ?>
	</div>

	<div class="left full">
		<br/>
		<h2>Lokalizacja naszej siedziby</h2>
		<iframe width="610" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://mapy.google.pl/maps?f=q&amp;source=s_q&amp;hl=pl&amp;geocode=&amp;q=Ibisa+14&amp;sll=52.141048,21.020708&amp;sspn=0.017515,0.038581&amp;ie=UTF8&amp;ll=52.141653,21.019893&amp;spn=0.007901,0.012875&amp;iwloc=A&amp;z=15&amp;output=embed"></iframe>	
	</div>
	
</div>