<div id="contact">

	<div class="half left">
    	<h1 class="borderBottom">Kontakt</h1>
    	
    	<p><strong>OMD Sp. z o.o.<br />oddział Optimum Media OMD</strong></p>
    	<p>ul. Ibisa 14<br />02-812 Warszawa</p>
    	<p>		
    		<strong>tel. (+4822) 32 01 200</strong><br />
    		fax: (+4822) 32 01 201<br />
    		mail: <a href="mailto:info@optimum-media.pl">info@optimum-media.pl</a>
    	</p>
    	<p>
    		NIP: 951 220 49 28<br />	
    		KRS: 000 027 24 33<br />
    		Sąd Rejonowy dla m. st. Warszawy<br />
    		XIII Wydział Gospodarczy KRS<br />
    		Kapitał: 26 235 500,00 zł
    	</p>
	</div>
	
	<div class="half left">
		<?php if( !$this->message ) :?>
		<form action="" method="post">
    		<h1 class="borderBottom">Formularz kontaktowy</h1>
    		
    		<p>Aby się z nami skontaktować możesz także wypełnić poniższy formularz:</p>
    		<p>
    			<label for="institution">Instytucja</label><br/>
    			<input class="text" type="text" name="institution" id="institution" />		
    		</p>
    		<p>
    			<label for="name">Imię i nazwisko</label><br/>
    			<input class="text" type="text" name="name" id="name" />	
    		</p>
				<p>
    			<label for="name">Stanowisko</label><br/>
    			<input class="text" type="text" name="position" id="position" />	
    		</p>
    		<p>
    			<label for="email">E-mail</label><br/>
    			<input class="text" type="text" name="email" id="email" />		
    		</p>
    		<p>
    			<label for="telephone">Telefon</label><br/>
    			<input class="text" type="text" name="telephone" id="telephone" />		
    		</p>
    		<p>
    			<label for="message">Wiadomość</label><br/>
    			<textarea class="text" name="message" id="message" rows="5"></textarea>		
    		</p>
            <p>
            	<input type="checkbox" name="copy" id="copy">
            	<label for="copy">Prześlij kopię tej wiadomości na swój e-mail</label>
            </p>
    		<p><input class="right" type="submit" value="Wyślij" /></p>
		</form>
		<?php else :?>
			<p class="center"><br/><br/><br/><br/><br/><?php echo $this->message ?></p>
		<?php endif; ?>
	</div>

	<div class="left full">
		<br/>
		<h2>Lokalizacja naszej siedziby</h2>
		<iframe width="610" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://mapy.google.pl/maps?f=q&amp;source=s_q&amp;hl=pl&amp;geocode=&amp;q=Ibisa+14&amp;sll=52.141048,21.020708&amp;sspn=0.017515,0.038581&amp;ie=UTF8&amp;ll=52.141653,21.019893&amp;spn=0.007901,0.012875&amp;iwloc=A&amp;z=15&amp;output=embed"></iframe>	
	</div>
	
</div>