<div id="tools">
	<h1>Narzędzia</h1>
	<a name="top"></a>
	<p class="paragraph borderBottom">Optimum Media OMD korzysta z dostępnych na rynku badań mediów oraz analiz zachowań konsumentów, jednak na bieżąco także śledzi nowe możliwości i trendy rozwoju mediów, by oferować swoim Klientom jak najciekawsze i za razem efektywne rozwiązania w planowaniu kampanii w mediach. W tym celu uczestniczy w budowie i inspiruje zespół Software Development do tworzenia narzędzi planerskich dopasowanych do realiów polskiego rynku i polskich konsumentów. Dodatkowo dzięki lokalnym projektom badawczym zespół Optimum Media OMD pogłębia wiedzę nt. efektywności mediów i dopasowania komunikacji do konkretnych założeń marketingowych Klientów.</p>
	<h2>Własne projekty badawcze</h2>
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/omniscope.png" alt="Omniscope logo" />
		<h4>Omniscope</h4>
		<p>Wielotematyczne badanie omnibusowe OMD Metrisc, realizowane na ogólnopolskiej próbie miejskiej. Projekt Omniscope otwiera Klientom możliwość zlecania pojedyńczych pytań o dowolnie określonej tematyce bez konieczności zlecania odrębnego badania.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/mindscope.png" alt="Mindscope logo" />
		<h4>Mindscope</h4>
		<p>Badanie siły poszczególnych kanałów komunikacji dla danej grupy docelowej i kategorii produktów. Umożliwia określenie perswazyjności siły oddziaływania kanałów komunikacji (index perswazyjności).</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/brandscope.png" alt="Brandscope logo" />
		<h4>Brandscope</h4>
		<p>Identyfikacja najważniejszych wymiarów percepcji marek  w danej kategorii- odtworzenie pozycjonowania w odbiorze potencjalnych konsumentów, identyfikacja silnych i słabych stron. Analiza zmian w percepcji marki w wyniku przeprowadzonych działań reklamowych.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/lifescope.png" alt="Lifescope logo" />
		<h4>Lifescope</h4>
		<p>Badanie umożliwiające precyzyjne rozpoznanie "dnia z życia" grupy docelowej i dzięki temu precyzyjne osadzenie komunikatu w kontekście.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/mediascope.png" alt="Mediascope logo" />
		<h4>Mediascope</h4>
		<p>Stały projekt badawczy Macroscope, mający na celu pogłębianie wiedzy o efektywności kanałów komunikacji. Pierwsza część - badanie wpływu różnych mediów oraz ilości powtórzeń na budowanie zapamiętywania przekazu reklamowego. Przeprowadzona przez Macroscope w okresie czerwca-grudnia 2004. Rewolucyjne wyniki, podważające rutynowe podejście do planowania mediów.</p>
	</div>
	
	<div class="tool">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/brandtracking.png" alt="Brandtracking logo" />
		<h4>Brandtracking</h4>
		<p>Badania Brand Tracking, prowadzone przez OMD, służące do ciągłego monitorowania pozycji marki i jej konkurentów, ewaluacji wyników kampanii i stosowanych strategii mediowych. Macroscope oferuje swoim Klientom planowanie kampanii reklamowych oraz bieżącą optymalizację działań reklamowych w oparciu o wnioski wypływające z Brand Trackingu.</p>
	</div>
	
	<div class="tool singleUnderline" style="height: 120px;">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/marketscopepotential.png" alt="Marketscopepotential logo" />
		<h4>Market potential scope</h4>
		<p>Określa udział poszczególnych grup potencjalnych konsumentów w całkowitej konsumcji produktu (marki/kategorii produktowej). Ocenia wskaźnik potencjału konsumpcyjnego poszczególnych grup konsumenckich. Identyfikuje najważniejsze bariery w rozwoju konsumpcji marki/kategorii produktowej. Rekomenduje optymalny dobór grup celowych oraz strategii komunikacyjnej niwelującej wykryte bariery konsumpcji. Ponadto analizuje wpływy kampanii reklamowych nas strukturę udziału poszcególnych grup w konsumpcji produktu.</p>
	</div>
	
	<h2>Lokalne narzędzia OMD</h2>
	
	<div class="tool" style="height: 105px">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/adeffect.png" alt="AdEffect logo" />
		<h4>AdEffect</h4>
		<p>AdEffect jest narzędzie do analizy wyników modelu ekonometrycznego, prognozującego efekty świadomościowe kampanii w zależności od wybranych rozwiązań reklamowych. Narzędzie zostało opracowane przez <a href="http://www.omgmetrics.pl/?mod=adeffect">OMG Metrics</a> w ramach unikalnego projektu ekonometrycznego, opartego na wieloletnim monitoringu wpływu aktywności reklamowej na wskaźniki świadomości marek i reklam na polskim rynku.</p>
	</div>
	
	<div class="tool" style="height: 225px">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/tvwarrior2.png" alt="TV Warrior logo" />
		<h4>TV Warrior</h4>
		<p>TV Warrior to autorski program OmnicomMediaGroup do optymalizacji i planowania kampanii TV, zbudowany z 4 modułów wspierających zakup w poszczególnych etapach:
			<ul class="dotted paragraph">
				<li><strong>Moduł predykcji oglądalności</strong> - Umożliwia centralne i zautomatyzowane przewidywanie oglądalności przyszłych bloków reklamowych dla 9 stacji TV, ok. 15 tys. bloków, ok. 120 różnych grup celowych.</li>
				<li><strong>Moduł optymalizacji</strong> - Moduł wybiera optymalne breaki ze wszystkich stacji jednocześnie zamiast predefiniować udziały poszczególnych stacji. Udziały stacji są konsekwencją optymalizacji nie odwrotnie.</li>
				<li><strong>Moduł zakupu</strong> - Proces zarządzania kampanią: generowania, wysyłki, wprowadzania i aktualizacji zleceń jest zautomatyzowany. Pozwala to planerom OMG na realizowanie zamówień przed konkurencją, szczególnie ważną przy zakupie z cennika.</li>
				<li><strong>Moduł raportowania/kontroli</strong> - Integruje dane pochodzące z różnych źródeł (prebuy, badania mediów, dane finansowe, predykcje oglądalności) i automatycznie generuje raporty. Umożliwia to błyskawiczną reakcję na nieprzewidziane okoliczności i korekty planów oraz pełną kontrolę kampanii.</li>
			</ul>
			</p>
	</div>
	
	<div class="tool singleUnderline" style="height: 200px">
		<h3 class="red left" style="margin-right: 18px">Outdoor Media<br />Integrator</h3>
		<p style="margin-left: 0px">Aplikacja OMI jest innowacyjnym i unikatowym narzędziem do selekcji nośników i optymalizacji kampanii outdoorowych. Outdoor Media Integrator  to jedyne na rynku narzędzie służące do:
			<ul class="dotted paragraph">
				<li>optymalnego rozplanowania kampanii w obrębie danej aglomeracji, z możliwością efektywnej topograficznej selekcji ofert różnych typów nośników</li>
				<li>weryfikacji lokalizacji konfliktowych, np. nośników zlokalizowanych zbyt blisko siebie i oddziaływujących na te same strumienie ruchu odpowiedniego zaplanowania kampanii kierunkowych (z nośnikami naprowadzającymi na wybrany obiekt)</li>
				<li>dobór nośników do kampanii na podstawie ich bliskości względem strategicznych punktów w topografii miast tzw. POI, pozwalające na dobór nośników w miejscach największego prawdopodobnego zagęszczenia grupy docelowej.</li>
			</ul>
		</p>
	</div>
	
	<h2>Sieciowe narzędzia OMD</h2>
	
	<div class="tool" style="height: 150px">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/checkmate.png" alt="OMD Checkmate logo" />
		<h4>OMD Checkmat</h4>
		<p>OMD Checkmate to model strategicznego planowania mediów. Spójny system myślenia używany we wszystkich oddziałach OMD na świecie, który został opracowany na bazie współpracy z czołowymi międzynarodowymi firmami oraz agencjami kreatywnymi. o Celem OMD Checkmate jest rozwijanie innowacyjnych i efektywnych rozwiązań komunikacyjnych służących budowaniu marki i pozycji rynkowej Klientów.  Wyniki są efektem wspólnej zespołowej pracy Klienta, Agencji i Domu Mediowego. Odnosząc się do metafory szachów, "szach-mat" stanowi przewodnik strategicznego myślenia: dynamicznego analizowania sytuacji biznesowej, opracowania długofalowej strategii rozwoju i taktyk służących do jej realizowania.</p>
	</div>
	
	<div class="tool" style="height: 70px">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/curve2.png" alt="OMD Curve logo" />
		<h4>OMD Curve</h4>
		<p>Program do modelowania "energii marki" i określania optymalnej efektywnej częstotliwości na bazie wewnętrznych i zewnętrznych uwarunkowań strategii komunikacji.</p>
	</div>
	
	<div class="tool" style="height: 50px">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/viewer.png" alt="OMD Viewer logo" />
		<h4>OMD Viewer</h4>
		<p>Narzędzie dające możliwość śledzenia wyników badania Brand Traking.</p>
	</div>
	
	<div class="tool" style="height: 50px">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/pressplanner.png" alt="OMD PressPlanner logo" />
		<h4>OMD PressPlanner</h4>
		<p>Program optymalizujący i planujący kampanie prasowe w oparciu o surowe dane.</p>
	</div>
	
	<div class="tool" style="height: 50px">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/datareporter.png" alt="OMD DataReporter logo" />
		<h4>OMD DataReporter</h4>
		<p>Spójny system raportowania działań mediowych konkurencji, służący do przygotowania regularnych raportów i analiz ad-hoc.</p>
	</div>
	
	<div class="tool" style="height: 50px">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/response.png" alt="OMD Response logo" />
		<h4>OMD Response</h4>
		<p>Model planowania kampanii responsowych mających na celu generowanie interakcji z odbiorcą (infolinia, kupon) oraz pomiaru efektywności użytych kanałów komunikacji.</p>
	</div>
	
	<div class="tool" style="height: 50px">
		<img src="<?= $this->baseUrl; ?>/public/images/tools/palette.png" alt="OMD Palette logo" />
		<h4>OMD Palette</h4>
		<p>Pomaga planerom w podejmowaniu decyzji, poprzez lepszy wybór kanałów przekazu, lepsze tarpetowanie i lepszą selekcję mediów. Ponad to, w pełni dopasowywuje sie do wymagań klientów. Palette jest częścią Brain Boxu OMD.</p>
	</div>
	
</div>