<div class="naszePrace" id="naszePrace">
	<h2>Nasze prace</h2>
	
	<ul class="spis">
		<li><a href="#_1">1. USB Streaming</a></li>
        <li><a href="#_2">2. AV/IT</a></li>
        <li><a href="#_3">3. Nissan Primera – Kolorowa Kamera</a></li>
        <li><a href="#_4">4. Wprowadzenie Marki Heyah</a></li>
        <li><a href="#_5">5. Heyah Zaraża</a></li>
        <li><a href="#_6">6. Walentynki w Era Love</a></li>
        <li><a href="#_7">7. Wygraj Olimpiadę</a></li>
	</ul>
	<br/>
	
	<div class="praca">
		<h3>USB Streaming</h3>

		<h4>Cel kampanii</h4>
		<ul>
			<li>Umocnienie Sony na pozycji lidera w segmencie kamer.</li>
			<li>Skierowanie uwagi grupy celowej na kamerę SONY z opcją USB Streaming łączącej funkcję kamery internetowej (współpracującej z komputerem) z kamerą klasyczną.</li>
		</ul>
		
		<h4>Działanie</h4>
		<ul>
			<li>Wykorzystane media w komunikacji:<br/>Radio (stacje: Radio ZET, RMF FM) – w jednym bloku pojawiały się 2 spoty. Pierwszy spot pojawiał się na uprzywilejowanej pierwszej pozycji i zawierał pytania przypominające klasyczne audiotele: “Szanowni słuchacze, jaka to funkcja, którą posiadają cyfrowe kamery Sony: EKG Streaming, USG Streaming, EKG Streaming, AGD Streaming, czy może USB Streaming? Odpowiedź po krótkiej przerwie.” Potem następowały reklamy innych firm i pojawiał się nasz drugi spot: "Pamiętaj to cyfrowe kamery Sony posiadają funkcję USB Streaming...i to jest prawidłowa odpowiedź!!!!!"</li>
			<li>Punktem wyjścia dla koncepcji kreacji była konstrukcja planu mediowego. Wykonaniem zajęła się agencja Saatchi & Saatchi stając na wysokości zadania.</li>
		</ul>

		<h4>Rezultat</h4>
		<ul>
			<li>USB Streaming było komunikowane wyłącznie w tej kampanii. W związku z tym można bez wątpliwości stwierdzić, że zainteresowanie kamerami w sklepach było spowodowane właśnie tą akcją. W okresie kampanii i tuż po, wielu klientów pytało właśnie o “ten Streaming”. Sukces był tak duży, że dział sprzedaży i dealerów Sony nagrodził dział marketingu SONY "owacjami na stojąco".</li>
		</ul>
	</div>
	
	<div class="praca">
		<h3>AV/IT</h3>

		<h4>AV/IT brief</h4>
		
		<p>Produkty Sony zostały zaprojektowane w taki sposób, by ich łączenie ze sobą było proste i intuicyjne, a jednocześnie umożliwiało komunikację w środowisku cyfrowym zarówno dla początkujacych, jak i zaawansowanych entuzjastów. Mogą oni kręcić filmy, montować je i rozpowszechniać w  formacie DVD na cyfrowej kamerze wideo, odtwarzaczu/rekorderze DVD oraz komputerze, a także oglądać je za pomocą telewizora Wega, gwarantującego doskonałą jakość obrazu.</p>
		<p>Mogą też tworzyć własne kompilacje nagrań z Internetu na urządzeniach typu Net MD Walkman™ lub CD za pomocą komputera i sprzętu audio Sony współpracującego z Internetem. Jeśli użytkownik dysponuje aparatem cyfrowym, komputerem oraz drukarką wideo, może tworzyć, przechowywać i drukować najwyższej jakości zdjęcia cyfrowe, a następnie przekazywać je za pośrednictwem karty Memory Stick™ bez użycia jakiegokolwiek kabla. Łatwa komunikacja łączy produkty audiowizualne z informatycznymi i pozwala ich użytkownikom w pełni kontrolować cyfrowe środowisko.</p>
		
		<h4>AV/IT opis</h4>
		<ul>
			<li>Wykorzystane media w komunikacji:<br/>Wizerunkowa kampania Sony promująca i wyjaśniająca wartość dodaną, jaką oferuje łączenie produktów Sony objęła swym zasięgiem: prasę, outdoor oraz internet. </li>
			<li>PW odniesieniu do ostatniego medium zastosowano różne formy reklamy:Top Layer, BrandMark, Skyscraper, Baner oraz mailingi targetowane: do młodzieży (Interia, O2) i dojrzałych użytkowników internetu (WP, Onet.pl).</li>
			<li>Wszystkie wymienione formy aktywności nawiązywały layoutem do kreacji prasowych i outdoorowych.</li>
			<li>Po raz pierwszy w Polsce wykorzystano dwa nowe rozwiązania: black & white i bluring, które powstały w OMD International.</li>
		</ul>

		<h4>Rezultat</h4>
		<ul>
			<li>USB Streaming było komunikowane wyłącznie w tej kampanii. W związku z tym można bez wątpliwości stwierdzić, że zainteresowanie kamerami w sklepach było spowodowane właśnie tą akcją. W okresie kampanii i tuż po, wielu klientów pytało właśnie o “ten Streaming”. Sukces był tak duży, że dział sprzedaży i dealerów Sony nagrodził dział marketingu SONY "owacjami na stojąco"</li>
		</ul>
	</div>
</div>
