<div id="omdschool">
    <h1 class="borderBottom"><?php echo $this->article->getTitle() ?></h1>
<div class="left">
<?php echo $this->article->getContent() ?>
</div>

<div class="right">
	<a target="_blank" href="http://www.omdschool.pl"><img class="paragraph" src="public/images/omdschool2.png" alt="OMD School" /></a>
	<p>Szczegóły dotyczące poszczególnych szkoleń znajdziecie Państwo na stronie: <a target="_blank" href="http://www.omdschool.pl">www.omdschool.pl</a></p>
</div>

</div>
