<div class="omdschool">
    <h2>OMD School</h2>
    
    <p>OMD School to uznana na rynku usług marketingowych szkoła, która specjalizuje się w organizacji i prowadzeniu profesjonalnych treningów z zakresu planowania i realizowania kampanii reklamowych w mediach, produkcji filmów reklamowych oraz stosowania product placement w marketingu, badań marketingowych, marketingu szeptanego, jak również strategii pozycjonowania marki. W swojej ofercie proponuje także warsztaty brandingowe, szkolenia poligraficzne, a także prezentujące nowe trendy i perspektywy w zakresie wykorzystywania mediów tradycyjnych, jak i niestandardowych rozwiązań.</p>
    <p>OMD School istnieje na rynku od 1999 roku. W ciągu 9 lat działalności przeszkoliliśmy ponad 1000 osób i liczba ta nieustannie rośnie a szkolenia cieszą się coraz większym zainteresowaniem.</p>
    <p>Jeśli chcesz zapoznać się z pełną ofertą szkoleń organizowanych przez OMD School zapraszam na stronę <a href="http://www.omdschool.pl" target="_blank">www.omdschool.pl</a>.</p><br/>
    
    <p class="address">
    	<img class="right" src="public/images/omdschool.jpg" alt="OMD School" />
    	Magdalena Kalbarczyk<br/>
    	direct: +48 22 32 01 105<br/>
    	mobile: +48 698 612 090<br/>
    	tel: +48 22 32 01 100<br/>
    	<a href="mailto:Magdalena.Kalbarczyk@OmnicomMediaGroup.pl">Magdalena.Kalbarczyk@OmnicomMediaGroup.pl</a>
    </p>
</div>