<h1 class="borderBottom">Sieć OMD</h1>

<p>Optimum Media OMD jest jednym z oddziałów OMD – międzynarodowej sieci domów mediowych operującej na około 100 rynkach każdego z regionów świata. OMD należy do jednego z największych holdingów komunikacyjnych na świecie – OmnicomGroup, notowanego na Nowojorskiej Giełdzie Papierów Wartościowych.</p>

<p>
Według The Gunn Report for Media OMD to najbardziej kreatywna agencja na świecie (the "Most Creative Media Agency in the World"), utytułowana także przez Adweek jako “Global Media Agency” of the Year oraz przez Campaign uznana za Media Network of the Year.
</p>

<p><a href="http://www.omd.com">Dowiedz się więcej >></a></p>

<div class="FlashMap">
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0" width="500" height="216" id="omd-location-map" align="middle">
		<param name="allowScriptAccess" value="sameDomain" />
		<param name="movie" value="omd-location-map.swf" />
		<param name="quality" value="high" />
		<param name="wmode" value="transparent" />
		<param name="scale" value="noborder" />
		<embed src="public/images/omd-location-map.swf" name="omd-location-map"
		type="application/x-shockwave-flash" quality="high" loop="true"
		width="500" height="216"
		align="middle" wmode="transparent"
		allowScriptAccess="sameDomain" pluginspage="http://www.macromedia.com/go/getflashplayer" />
	</object>

</div>


<a target="_blank" href="http://www.omd.com"><img src="<?= $this->baseUrl; ?>/public/images/omd.gif" alt="OMD School" /></a>