<div class="zespol">
	<h2>Zespół</h2>
	<p><strong>Asia Pacific Leadership Strength</strong></p>
	<p>OMD Asia Pacific was established in November 1997 and is now present in 13 Asia Pacific countries with19 offices. The region is overseen by <a href="barry-cupples.html">Barry Cupples</a>, CEO, Omnicom Media Group, Asia Pacific, - based in Singapore - and <a href="maggie-choi.html">Maggie Choi</a>, Managing Director, OMD, Asia Pacific - based in Hong Kong. The Community Champions oversee their disciplines across all markets, driving best practice and ensuring the bar is constantly being raised throughout the network. Strategic Planning, Digital, Buying and Research Communities meet regularly to discuss issues, brainstorm new ideas and ensure the critical application and standards of OMD Checkmate. This community structure facilitates the speed of communication and guarantees the effective and efficient transfer of client information to make sure things get done.</p>
	<img src="public/images/zespol_asia.jpg" alt="Zespól" />
	
</div>


