<div class="topBlock">
	<div class="twitter">
		<p class="noBorder">
			Sprawdź nas na <a href="http://twitter.com/optimummediaomd" target="_blank">
				<img src="<?= $this->baseUrl; ?>/public/images/twitterlogo.png" alt="Logo Twittera" id="twitter" />
			</a>
		</p>
	</div>
	<div class="something">
			<?php if( sizeof($this->tweets )) : ?>
				<?php for( $i = 0, $cnt = sizeof($this->tweets); $i < $cnt; $i++ ) :?>
					<p id="tweet<?= $i; ?>" <?= ($i==0)?'':'style="display:none"'?>><a href="http://twitter.com/optimummediaomd" target="_blank"><?php echo $this->tweets[$i] ?></a></p>
				<?php endfor ?>
			<?php endif; ?>
	</div>
</div>

<?php if( count($this->addNews) ) : ?>
<div class="news">
	<h3>Aktualności</h3>
	<?php for( $i = 0, $cnt = count( $this->addNews ); $i < $cnt; $i++ ) :?>
		<p id="short<?= $i; ?>" <?= ($i==0)?'':'style="display:none"'?>><a href="<?= $this->baseUrl; ?>/aktualnosci.html"><?php echo $this->addNews[$i] ?></a></p>
	<?php endfor ?>
</div>
<?php endif; ?>