   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keyword" content="OMD, Optimum Media OMD, dom mediowy, domy mediowe, media, optymalizacja, optymalizować, optymalne kampanie, efektywność, efektywny, efektywnie, skuteczny, skutecznie, badania, analiza, analizy, kampania mediowa, Jakub Bierzyński, reklama, marketing, strategie mediowe, strategie marketingowe, komunikacja w mediach, telewizja, TV, prasa, radio, Internet, outdoor, kino, SEM">
      <title><?php echo $this->escape($this->title); ?></title>
			<style type="text/css" media="screen">
				@import url( <?= $this->baseUrl; ?>/public/styles/s00210.css );
			</style>
			<script type="text/javascript" src="<?= $this->baseUrl; ?>/public/scripts/omd.js" charset="utf-8"></script>			
   </head>