<div id="navigation">
	<ul>
		<li class="first"><a href="<?= $this->baseUrl; ?>/" class="hi"></a></li>
		<li><a href="<?= $this->baseUrl; ?>/o-nas.html">O nas</a></li>
		<li><a href="<?= $this->baseUrl; ?>/aktualnosci.html">Aktualności</a></li>
		<li><a href="<?= $this->baseUrl; ?>/zespol.html">Zespół</a></li>
		<li><a href="<?= $this->baseUrl; ?>/nasze-prace.html">Nasze prace</a></li>
		<li><a href="<?= $this->baseUrl; ?>/narzedzia.html">Narzędzie</a></li>
		<li><a href="<?= $this->baseUrl; ?>/analizy-i-publikacje.html">Anaizy i publikacje</a></li>
		<li><a href="<?= $this->baseUrl; ?>/omd-school.html">OMD School</a></li>
		<li><a href="<?= $this->baseUrl; ?>/siec-omd.html">Sieć OMD</a></li>
		<li><a href="<?= $this->baseUrl; ?>/kontakt.html">Kontakt</a></li>
	</ul>
</div>
